-- Recipe Manager Database Schema
-- PostgreSQL Migration Script
-- Run this to create all tables from scratch

-- Drop existing tables if they exist (in reverse order of dependencies)
DROP TABLE IF EXISTS shopping_list_items CASCADE;
DROP TABLE IF EXISTS shopping_lists CASCADE;
DROP TABLE IF EXISTS meal_plan_entries CASCADE;
DROP TABLE IF EXISTS recipe_tags CASCADE;
DROP TABLE IF EXISTS recipe_ingredients CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS ingredients CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ============================================
-- USERS TABLE
-- ============================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- INGREDIENTS TABLE
-- ============================================
CREATE TABLE ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

-- ============================================
-- RECIPES TABLE
-- ============================================
CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    image_url VARCHAR(500),
    instructions TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX ix_recipes_user_id ON recipes(user_id);
CREATE INDEX ix_recipes_user_id_title ON recipes(user_id, title);

-- ============================================
-- TAGS TABLE
-- ============================================
CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX uq_tags_user_id_name ON tags(user_id, name);
CREATE INDEX ix_tags_user_id ON tags(user_id);

-- ============================================
-- RECIPE_INGREDIENTS TABLE (Junction)
-- ============================================
CREATE TABLE recipe_ingredients (
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
    quantity DECIMAL(10, 2),
    unit VARCHAR(50),
    note VARCHAR(255),
    PRIMARY KEY (recipe_id, ingredient_id)
);

CREATE INDEX ix_recipe_ingredients_ingredient_id ON recipe_ingredients(ingredient_id);

-- ============================================
-- RECIPE_TAGS TABLE (Junction)
-- ============================================
CREATE TABLE recipe_tags (
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (recipe_id, tag_id)
);

CREATE INDEX ix_recipe_tags_tag_id ON recipe_tags(tag_id);

-- ============================================
-- MEAL_PLAN_ENTRIES TABLE
-- ============================================
CREATE TABLE meal_plan_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    week_start_date DATE NOT NULL,
    day_of_week INT NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
    meal_slot VARCHAR(50) NOT NULL,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_meal_plan_entries_user_id ON meal_plan_entries(user_id);
CREATE INDEX ix_meal_plan_entries_user_id_week_start_date ON meal_plan_entries(user_id, week_start_date);
CREATE UNIQUE INDEX uq_meal_plan_entries_user_week_day_slot ON meal_plan_entries(user_id, week_start_date, day_of_week, meal_slot);

-- ============================================
-- SHOPPING_LISTS TABLE
-- ============================================
CREATE TABLE shopping_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    week_start_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_shopping_lists_user_id_week_start_date ON shopping_lists(user_id, week_start_date);

-- ============================================
-- SHOPPING_LIST_ITEMS TABLE
-- ============================================
CREATE TABLE shopping_list_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_id BIGINT NOT NULL REFERENCES shopping_lists(id) ON DELETE CASCADE,
    ingredient_id BIGINT NOT NULL REFERENCES ingredients(id),
    total_quantity DECIMAL(10, 2),
    unit VARCHAR(50),
    purchased BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX ix_shopping_list_items_shopping_list_id ON shopping_list_items(shopping_list_id);
CREATE INDEX ix_shopping_list_items_ingredient_id ON shopping_list_items(ingredient_id);
CREATE UNIQUE INDEX uq_shopping_list_items_list_ingredient ON shopping_list_items(shopping_list_id, ingredient_id);

-- ============================================
-- COMMENTS
-- ============================================
COMMENT ON TABLE users IS 'Stores user accounts';
COMMENT ON TABLE recipes IS 'Stores recipe information';
COMMENT ON TABLE ingredients IS 'Master list of ingredients';
COMMENT ON TABLE recipe_ingredients IS 'Links recipes to their ingredients with quantities';
COMMENT ON TABLE tags IS 'User-defined tags for organizing recipes';
COMMENT ON TABLE recipe_tags IS 'Links recipes to tags';
COMMENT ON TABLE meal_plan_entries IS 'Weekly meal planning entries';
COMMENT ON TABLE shopping_lists IS 'Shopping lists generated from meal plans';
COMMENT ON TABLE shopping_list_items IS 'Individual items in a shopping list';

COMMENT ON COLUMN meal_plan_entries.day_of_week IS '0=Monday, 1=Tuesday, ..., 6=Sunday';
COMMENT ON COLUMN meal_plan_entries.meal_slot IS 'breakfast, lunch, dinner, or snack';
