-- Migration: Add email verification and onboarding support
-- Run this after 001_initial_schema.sql

-- Add name column to users table (required for new signups)
ALTER TABLE users
ADD COLUMN IF NOT EXISTS name VARCHAR(255);

-- Set default name for existing users (use email prefix)
UPDATE users SET name = split_part(email, '@', 1) WHERE name IS NULL;

-- Make name NOT NULL after setting defaults
ALTER TABLE users ALTER COLUMN name SET NOT NULL;

-- Add new columns to users table
ALTER TABLE users
ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE;

-- Create email_verification_codes table
CREATE TABLE IF NOT EXISTS email_verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code VARCHAR(6) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_email_verification_codes_user_id ON email_verification_codes(user_id);
CREATE INDEX IF NOT EXISTS ix_email_verification_codes_expires_at ON email_verification_codes(expires_at);

-- Create user_preferences table
CREATE TABLE IF NOT EXISTS user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    preference_type VARCHAR(20) NOT NULL CHECK (preference_type IN ('diet', 'cuisine')),
    tag_name VARCHAR(100) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_user_preferences_user_id ON user_preferences(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_preferences_user_type_tag ON user_preferences(user_id, preference_type, tag_name);

-- Update existing users to be verified (for backwards compatibility)
UPDATE users SET email_verified = TRUE, onboarding_completed = TRUE WHERE email_verified = FALSE;

COMMENT ON TABLE email_verification_codes IS 'Stores 6-digit email verification codes with expiry';
COMMENT ON TABLE user_preferences IS 'Stores user dietary and cuisine preferences from onboarding';
